option(ENABLE_SHARED "Build shared libraries" ON)
if (DEFINED TOP_NAMESPACE)
    set(TOP_NAMESPACE ${TOP_NAMESPACE} CACHE STRING "Top level namespace")
else()
    set(TOP_NAMESPACE "simpleRt" CACHE STRING "Top level namespace")
endif()

macro(print_config)
    include(BuildInfo)
    # Get git info
    set(GIT_HASH "")
    get_git_hash(GIT_HASH)
    # git_BRANCh
    set(GIT_BRANCH "")
    get_git_branch(GIT_BRANCH)
    message("------------------------------------------------------------------------")
    message("-- Configuring   ${PROJECT_NAME} ${PROJECT_VERSION}")
    message("------------------------------------------------------------------------")
    message("-- CMake         Cmake version and location   ${CMAKE_VERSION}")
    message("-- Compiler      C++ compiler version         ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
    message("-- Build type    Target type                  ${CMAKE_BUILD_TYPE}")
    message("-- Platform      Target platform              ${CMAKE_HOST_SYSTEM_PROCESSOR}/${CMAKE_HOST_SYSTEM}")
    message("-- Git           Git branch/commit            ${GIT_BRANCH}/${GIT_HASH}")
    message("------------------------------------------------------------------------")
    message("-- Build shared  Build shared libraries       ${ENABLE_SHARED}")
    message("------------------------------------------------------------------------")
endmacro()
